// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cszgrmcqwginysxebsgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzemdybWNxd2dpbnlzeGVic2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDYzMjQsImV4cCI6MjA2MTc4MjMyNH0.wmGW4yLFNz-31tPzYcEjx1QqITWhXkoaUuiKQIWmoNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);